---
base_timezone: "America/New_York"

admin_user_name: "smittyman"
admin_user_groups:
  - sudo

admin_passwordless_sudo: true
admin_authorized_key_file: "/mnt/c/Users/1973m/.ssh/id_ed25519.pub"
admin_console_password_enabled: false
